FROM python:3.8-buster

LABEL maintainer="Cláudio Pereira <supernova@claudiop.com>"

COPY pip-packages /
RUN apt update \
    && apt install  -y --no-install-recommends git sqlite libgdal20 \
    && pip install --no-cache-dir --trusted-host pypi.python.org -r /pip-packages \
    && rm -rf /var/lib/apt/lists/* /pip-packages \
    && apt remove -y gcc

VOLUME  ["/conf", "/source", "/http"]
WORKDIR /source
EXPOSE 1893
ENTRYPOINT ["uwsgi", "/conf/uwsgi-dev.ini"]
