from api.views import college
from api.views import groups
from api.views import chat
from api.views import news
from api.views import services
from api.views import store
from api.views import learning
from api.views import users
from api.views import calendar
from api.views import third_party
